### ISSUE TITLE
support for received messages?

### ISSUE THREAD

**Issue by mlanci** [endel/NativeWebSocket#16]
Hello, I'm able to connect, disconnect and send messages but is there any support for receiving messages from another client?

**Comment by endel** [comment]
That's not how WebSocket's work. WebSocket enables bidirectional communication between a WebSocket client and a WebSocket server. To make a client talk to each other, the server must be the one that's going to pass the message from one client to another.

**Comment by mlanci** [comment]
That's what I meant, a passthru. Using client 1 to talk to client 2 thru API gateway on AWS. But I'm unsure if I send a message from API gateway to Unity -- how is my unity client listening for that message from the server?

**Comment by endel** [comment]
I don't have experience this service from AWS, but you can play around with the example server on this repository. You would keep track of the `ws` instances of each client, and use `ws.send()` for the other client, similar to what's going on here (on this example it sends only for the current client, but each client has it's own `ws` instance): https://github.com/endel/NativeWebSocket/blob/66b67f78f235164e5cf1f5057fcced17f64b6a66/NodeServer/index.js#L15
