### ISSUE TITLE
Where is the dll?

### ISSUE THREAD

**Issue by davvit** [endel/NativeWebSocket#21]
I am new to unity,
How do i import this library into my project?

![image](https://user-images.githubusercontent.com/4433698/94296353-5222ab80-ff28-11ea-8b8e-8f90e914d4f3.png)

**Comment by endel** [comment]
Just download & copy this folder into your project: https://github.com/endel/NativeWebSocket/tree/master/NativeWebSocket/Assets/WebSocket
