### ISSUE TITLE
Please make Unity Package

### ISSUE THREAD

**Issue by benukhanov** [endel/NativeWebSocket#23]
Hey!

Thanks a lot for the native web socket. I'd ask you to create a "package.json" file so that we can add this package via git url to our Unity package manager.

See example with in my repository [ui-manager](https://github.com/benukhanov/ui-manager). I also have a CI (GitHub Actions) that adds the latest commits to the upm branch.

If you want, I can contribute and make this repository the same as ui-manager so that we can use NativeWebSocket as a package instead of adding it to the Assets folder.

**Comment by endel** [comment]
Hi @benukhanov 👋 this would be a really nice addition. A PR is very welcome for this!

**Comment by benukhanov** [comment]
> Hi @benukhanov  this would be a really nice addition. A PR is very welcome for this!

Awesome! Tomorrow I'll do some PR.

**Comment by benukhanov** [comment]
@endel Hey!

Sorry for the delay, I had unexpected things to do. Anyway, there is #25 and I tested it with a forked repository, so everything works fine. :smiley:
