### ISSUE TITLE
How can I use it in Unity 2018.1.4f1

### ISSUE THREAD

**Issue by Ezharjan** [endel/NativeWebSocket#31]
When I opened your demo in Unity 2020, I exported a Unity package aiming to use it in Unity 2018, but I encountered incompatibility problems, detail is shown on screenshot below. I know that you have noted in README file about the compatibility problem, but I am hoping to use one just like yours in 2018 version of Unity. May you gitve me some advice? Or may you make it open source and compatible with 2018 version?

![图片](https://user-images.githubusercontent.com/60126466/105793919-f4c96480-5fc4-11eb-8cc1-497c00614566.png)

<br>
<br>
<br>

Plus, a very funny thing in your demo is that you added RigidBody component onto Camera, camera will be falling down once the scene is played.
![图片](https://user-images.githubusercontent.com/60126466/105793367-f47c9980-5fc3-11eb-9a32-2a7e70849515.png)

**Comment by endel** [comment]
Hi @Ezharjan,

This library requires that your C# project is capable of importing `System.Net.WebSockets` (available in the .NET 4.x+ Runtime)

I'm not sure this is possible on Unity 2018. I'd recommend upgrading.

**Comment by Ezharjan** [comment]
Thanks!
