### ISSUE TITLE
Cannot build for WebGL when installed via UPM

### ISSUE THREAD

**Issue by Geekid812** [endel/NativeWebSocket#35]
Unity fails to build for WebGL with the following errors when the package was installed with UPM:
![image](https://user-images.githubusercontent.com/52078482/106146992-a4463880-6177-11eb-81d7-9a8b32036212.png)

This does not happen when installed manually nor when building for other platforms (tested with standalone).

**Comment by endel** [comment]
Hi @Geekid812, this has been just fixed now at https://github.com/endel/NativeWebSocket/pull/34

Can you try again? 🙏

**Comment by Geekid812** [comment]
Hey, sorry for the late reply. Yes! This does fix the issue. Thank you! 👍
