### ISSUE TITLE
Building for Android: error: dlopen failed: library "advapi32" not found"

### ISSUE THREAD

**Issue by nicktucci** [endel/NativeWebSocket#4]
Received this error in a large project when building for Android. To test I made a fresh project with only NativeWebSocket and a Connection demo script.

Built for Android in Unity 2019.3.1f1 I am getting the following error:

> Plugins: Couldn't open advapi32, error: dlopen failed: library "advapi32" not found

This error prints twice and then the project runs normally. 
It doesn't seem to affect the library from running as expected.

**Comment by endel** [comment]
Hi @nicktucci, I'm not sure this error is related to `NativeWebSocket`.

Here's some threads I've found about this:
- https://github.com/neuecc/MessagePack-CSharp/issues/748
- https://forum.heroiclabs.com/t/unity-2019-2-background-exception-when-socket-connects/361/22

**Comment by nicktucci** [comment]
I'm confident it is in some part caused by NWS because I don't receive the error when building the test project without including the demo connection script on a GameObject. 

It has so far proved benign however so I'm closing the issue.
