### ISSUE TITLE
Can i send string and bytearray together?

### ISSUE THREAD

**Issue by Matt-Finlay** [endel/NativeWebSocket#59]
The API I'm trying to use, wants me to send data in the following manor:

`websocket.emit("binaryData", data);`

Does NativeWebSockets support this? or can i only sent plain text OR byteArray separately?

Thanks

**Comment by endel** [comment]
Hi @Matt-Finlay, with raw WebSocket communication you either send arbitrary binary or text messages. Message types as you've described must be implemented on your own. Most higher-level abstractions over WebSocket support this, though. Such as [socket.io](https://socket.io/) and [Colyseus](https://github.com/colyseus/colyseus).
