### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by rakeshparihar** [endel/NativeWebSocket#61]
Using Reserve seat API to join in a room, and when there is a  WebSocket connection drops unexpectedly, its not reconnecting and getting an error " The remote party closed the WebSocket connection without completing the close handshake." with error code : 1006.

Step to reproduce:
1. Join room by Seat reserve call - (Independent of matchmaking of Colyseus)
2.  After successful seat reserve call
3. Ping pong should be started 
4. Once get connected try to close the internet for a few seconds or if your internet gets disconnected for some reason.
you will get the issue right there

**Comment by endel** [comment]
Hi @rakeshparihar, I've moved this to https://github.com/colyseus/colyseus-unity3d/issues/185 as your report is related to Colyseus directly
