### ISSUE TITLE
Is it possible  to emit?

### ISSUE THREAD

**Issue by Jsennin1** [endel/NativeWebSocket#7]
If i have 

```
websocket.on('matchsearching',function(data){
//server side
//do something
});
```
in server side, can i emit in client side with this like 

```
websocketClient.emit('matchsearching', data);
//client side
```
Is that possible ?

**Comment by endel** [comment]
Hi @Jsennin1, this library is a plain WebSockets wrapper, it does not provide any additional behaviour such as messages by type.

If you're building a game, I highly recommend using Colyseus - which uses this WebSocket client under the hood: 
- https://github.com/colyseus/colyseus
- https://github.com/colyseus/colyseus-unity3d

**Comment by Jsennin1** [comment]
thanks. It looks nice
