### ISSUE TITLE
does it work only as websocket client?

### ISSUE THREAD

**Issue by virtouso** [endel/NativeWebSocket#85]
hi. 

i also need my web socket server to be a unity3d app to push scores and rankings regularly to the players. 

can i also make my server using this package?

**Comment by endel** [comment]
Hi @virtouso, this lib is just a WebSocket **client**. I'd recommend using an actual server for this. 
For an authoritative server I'd recommend Colyseus 😇

**Comment by virtouso** [comment]
@endel  thank you for the fast reply. 

if it was a turn-based or not a real-time game with per frame update, your suggestion is right, there is no need for a unity server. my preference is .net signalR.

but its a real-time UDP game that Unity server should hold the authority. but I still need a WebSocket server inside my Unity server to push scores and big metadata to the clients.
